### ISSUE TITLE
[Feature] Federated Authentication provider support

### ISSUE THREAD

**Issue by bambamalicious** [rommapp/romm#580] opened 2024-01-07 22:05 UTC
**Is your feature request related to a problem? Please describe.**
The ability to use federated authentication such as active directory would allow for SSO within networks.

**Describe the solution you'd like**
Federated authentication support such as Entra ID or AD FS

I understand if its a big ask and doesn't get implemented, but it would be a nice facility to have for those using AD at home etc.

**Comment by jhotmann** [comment] 2024-01-26 17:47
Adding on to this with some examples of other self-hosted auth strategies: [Trusted Header](https://www.authelia.com/integration/trusted-header-sso/introduction/) and [OIDC](https://openid.net/developers/how-connect-works/)

**Comment by chandz05** [comment] 2024-03-12 18:15
Would love OIDC support

**Comment by cstby** [comment] 2024-04-01 06:38
Other self-hosted python apps like [tandoor](https://github.com/TandoorRecipes/recipes) have used [django-allauth](https://docs.allauth.org/en/latest/index.html) very effectively. I'm not familiar with the details of RomM's tech stack, but this could be a straightforward way to get OIDC.

**Comment by gantoine** [comment] 2024-12-24 00:36
Closing this as (mostly) a duplicate of #540, and the fact that we won't be tackling Entra ID/ADFS.

**Closed by gantoine** 2024-12-24 00:36 UTC
Labels: feature
