### ISSUE TITLE
[Bug] RomM Only Indexing Files Within Root Folder and Not The Sub Folder of PC Games

### ISSUE THREAD

**Issue by MightyRufo** [rommapp/romm#1375] opened 2024-12-22 23:13 UTC
**RomM version**
3.6.0

Describe the bug
RomM isn’t scanning subfolders for PC games. It only sees files in the base folder, ignoring any subfolders like “Game,” or “Patch.”

To Reproduce

Set up RomM with a platform named pc.
Place a base folder with subfolders inside (e.g., The Sims 3 → Game, Patch).
Run a complete scan in RomM.
Observe that it only detects files in the base directory and skips the subfolders.
Expected behavior
We expect RomM to recursively scan all subfolders so that game sizes reflect the real amount and downloads work properly.

Desktop (please complete the following information):

OS: Windows 11
Browser: Chrome
Version: 131.0

Additional context
Tried multiple config tweaks (like multi_file entries, removing the roms_folder path, etc.) but RomM still won’t detect subfolders beyond the base level.

**Comment by gantoine** [comment] 2024-12-22 23:17
We're tracking this as part of wider, ongoing work around file file structure and detection, so I'm going to close this as a duplicate of an internal (private) ticket.

**Closed by gantoine** 2024-12-22 23:17 UTC
Labels: bug
