### ISSUE TITLE
[Bug] Rename function struggles with special characters

### ISSUE THREAD

**Issue by Casuallynoted** [rommapp/romm#392] opened 2023-10-05 00:08 UTC
I've noticed that sometimes the rename file function leaves the roms with really weird names in the file explorer. In this example, the PC game Babylon 5: Into the Fire has been renamed to BDY6C8~Q.ZIP

But what's weird is that the game still downloads in Romm and shows in the Romm editor as having the proper name.

I think this happens when I go to have it rename a game that has a character like : in the title, and I believe the reason is because my filesystem may not like : in file names. I've tried renaming these games manually via my server's SMB connection and it always errors out when a : is included in the name.

**Comment by GAntoine** [comment] 2023-10-07 20:39
Alight finally back home and I can look into this. Why file system are you using? FWIW it works fine on macos journaled and ubuntu ext4.

**Comment by Casuallynoted** [comment] 2023-10-07 20:51
I'm using a ZFS machine at the moment

**Comment by Alucardac1** [comment] 2023-11-07 15:15
So my current setup is having romM run via docker on Ubuntu ext4, I've noticed that if I use my Arch PC it renames correctly, however if I repeat the process from my Windows 10 Laptop, it ends up jumbled, likely due to colon being a invalid filename character on Windows systems.

It might be a better idea to adjust the renaming script to convert these characters to spaces or hyphens to avoid compatibility issues. I hear the same issues are being caused by slashes in names.

**Comment by Alucardac1** [comment] 2023-11-15 15:22
After some further testing, If I disable smb on the server and use only view the renamed files on my storage server (Ubuntu 23) where I host my roms, I no longer get truncated filenames if they contain cited characters.

**Comment by Nomelas** [comment] 2024-01-04 20:04
I am also experiencing this. I am on Unraid, and here's another example (genesis game):
Castlevania: Bloodlines

renames to:
CKMXO9~5.GEN

**Comment by annihilatethee** [comment] 2024-02-26 19:22
Windows definitely does not allow colons in names. I'm seeing the same with the following.

Legend of Zelda: Breath of the Wild
Legend of Zelda: Tears of the Kingdom
Mario Golf: Super Rush
Mario Striker: Battle League
Pokemon Legends: Arceus

Would love to see a rename that disregards colons.

**Comment by BACONGUDEN** [comment] 2024-06-23 12:27
> Windows definitely does not allow colons in names. I'm seeing the same with the following.
> Would love to see a rename that disregards colons.

Seconding this, just had a panic attack thinking half of my roms just disappeared, turns out they were just renamed with colons in the file names.

It's also just ethical programming to not have special characters in file names to begin with.

**Comment by gantoine** [comment] 2024-06-23 16:53
> It's also just ethical programming to not have special characters in file names to begin with.

To be fair, we don't typically use special characters in any files we create; this is a side-effect of users running RomM under Windows, which we didn't expect and don't recommend. We do cleanup file names which are invalid on most common linux filesystems (and macos for development).

**Comment by BACONGUDEN** [comment] 2024-06-23 17:15
I am running RomM in a docker container on debian personally, but I also access the library using my Windows computer using NFS. I'm not sure if I am misunderstanding you but the special symbols issue happens on Linux as well.

Many users do it this way (hosting on linux but accessing library also on windows), which is why this "sanitize file name"-check should be added.

**Comment by Nomelas** [comment] 2024-06-23 18:25
I don't think this is not a problem with windows though, it's the game itself that has special characters and romm trying to rename it with those special characters that aren't supported in any OS. I run romm on Linux and have the same problem.

**Comment by Nomelas** [comment] 2024-06-23 18:29
> > It's also just ethical programming to not have special characters in file names to begin with.
> 
> To be fair, we don't typically use special characters in any files we create; this is a side-effect of users running RomM under Windows, which we didn't expect and don't recommend. We do cleanup file names which are invalid on most common linux filesystems (and macos for development).

As many pointed out, it's not isolated to running romm in Windows since most of us don't, and are experiencing this.

**Comment by Casuallynoted** [comment] 2024-06-23 19:01
I also run on Linux and experience this issue.

**Comment by gantoine** [comment] 2024-06-23 19:13
Well heard, I'm going to increase the priority of this so we can start working on a fix sooner. 🫡

**Comment by vodkapmp** [comment] 2024-08-20 02:01
> > It's also just ethical programming to not have special characters in file names to begin with.
> 
> To be fair, we don't typically use special characters in any files we create; this is a side-effect of users running RomM under Windows, which we didn't expect and don't recommend. We do cleanup file names which are invalid on most common linux filesystems (and macos for development).

![image](https://github.com/user-attachments/assets/5c1422cb-e392-43a5-9d6b-3436739c5daf)
The rename function when matching unmatched roms will use any character it wants, even a /. I don't think my filesystem would've liked this one.
Quite fun, I've seen it try and use just about every "illegal" character at this point while working on matching my entire PS1 collection.

**Comment by gantoine** [comment] 2024-08-29 20:41
Wowza, long time coming but this will _finally_ be fixed in the next release! Checkout #1109 if you want to see what changed.

**Closed by gantoine** 2024-08-29 20:41 UTC
Labels: bug, help wanted

**Comment by Nomelas** [comment] 2024-09-04 00:18
Confirmed fixed in 3.5!
