### ISSUE TITLE
[Bug] File permissions issues on stored resources

### ISSUE THREAD

**Issue by joestump** [rommapp/romm#458] opened 2023-11-11 04:35 UTC
**RomM version**
RomM2.1.0

**Describe the bug**

* All titles 400 from IGDB on scan.
* Scans never finish. Many platforms are ignored/skipped.
* It only saw `genesis` despite having many other platforms.

**To Reproduce**

I have a library structured like so:

```
library/
-> roms/
  -> genesis/
    'Xenon 2 - Megablast (Europe).md'
    'X-Men 2 - Clone Wars (USA, Europe).md'
    'X-Men (USA).md'
    'X-Perts (USA).md'
    'Yogi Bear - Cartoon Capers (Europe).md'
    'Ys III (USA).md'
    'Zany Golf (USA, Europe) (v1.1).md'
    'Zero the Kamikaze Squirrel (USA).md'
    'Zero Tolerance (USA, Europe).md'
```

This is all I see in the logs:

<img width="1068" alt="image" src="https://github.com/zurdi15/romm/assets/37667/9bbd7134-aa69-4b8d-beaa-d528251099d5">

**Expected behavior**

I wasn't expect exact name matching. I guess I was expecting something that would strip punctuation, normalize white space, and then see if there was an exact match? 

Looking for guidance on how to name files. The docs cover the directory structure and heavily imply you need to name your rom the same title as the IGDB title or it will fail to match? 400 usually indicates client error?

**Screenshots**

<img width="1424" alt="image" src="https://github.com/zurdi15/romm/assets/37667/9add2872-a190-4b7a-8467-ceb332538ed8">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefix
 - Version: 119.0 (64-bit)

**Smartphone (please complete the following information):**
N/A

**Additional context**
Guessing I'm missing something simple. Hoping I don't have to rename the entirety of my library. I have a couple of questions s well:

* What is the guidance when the same game has multiple verions? Use the subfolders shown in the README? (I'd assumed this was for games that literally had 2x physical CDs.)
* Will there be support for some of the common naming formats (these are from Internet Archive for instance)? 
* If not, could we get docs on the specifics of the best file naming strategies? 

Thanks for your efforts; stoked to use it once I work out the kinds 😄

**Comment by zurdi15** [comment] 2023-11-11 09:11
Hi! For what I see, the problem is that RomM is not recognizing the platforms because the naming of those platforms doesn't match the IGDB slug. 

For example, for `genesis` folder you should rename it to `genesis-slash-megadrive` because that is how the genesis slug is in IGDB (you can go to the platform page in IGDB to check the slug in the url)

**Comment by joestump** [comment] 2023-11-12 21:07
@zurdi15 I was able to get games to identify, however the covers are all 400'ing:

```
ERROR:	  [RomM][2023-11-12 20:07:31] 400 Client Error: Bad Request for url: https://api.igdb.com/v4/covers/
ERROR:	  [RomM][2023-11-12 20:07:32] 400 Client Error: Bad Request for url: https://api.igdb.com/v4/screenshots/
```

<img width="1434" alt="image" src="https://github.com/zurdi15/romm/assets/37667/18d474eb-9e01-4c7c-93ee-61f8580c9042">

**Comment by joestump** [comment] 2023-11-12 21:14
The odd things is the covers are on disk. I checked the `resources` folder and they're in there.

**Comment by joestump** [comment] 2023-11-12 21:27
Seeing this in the logs, but the files are all `777` so not sure why it can't read the files.

```
2023/11/12 21:26:07 [crit] 17#17: *202 stat() "/var/www/html/assets/romm/resources/gbc/$game/cover/big.png" failed (13: Permission denied), client: 192.168.1.216, server: localhost, request: "GET /assets/romm/resources/gbc/$game/cover/big.png HTTP/1.1", host: "nuc02:8888"
```

**Comment by gantoine** [comment] 2023-11-13 01:04
Are you using a reverse proxy in front of your romm instance? And can you access images directly, like via another browser tab?

**Comment by joestump** [comment] 2023-11-13 01:10
The odd thing is the container can create the covers, but apparently can't read them? Directly preceding that log line is this log line: 

```
2023/11/13 01:07:36 [crit] 17#17: *257 stat() "/var/www/html/assets/romm/resources/ps2/Burnout Dominator/cover/big.png" failed (13: Permission denied), client: 192.168.1.216, server: localhost
```

Not really sure why the HTTP server can't read the cover file?

**Comment by zurdi15** [comment] 2023-11-14 15:21
Yeah seems like a filesystem permission issue. I run RomM behind npm (and other instande without proxy) and I didn't have any problem with that.

That said, I can't think in anything useful right now for you problem, as you said RomM can write the covers in the filesystem, so the issue is so weird :confused:

**Comment by joncrangle** [comment] 2023-12-30 05:45
Did you find a fix for this issue? I'm running into the same problem where covers and screenshots are being written to my drive, but I get permission denied when trying to read them in the frontend.

**Comment by gantoine** [comment] 2023-12-30 15:23
Just popping in to cross-link these two issues as they might be related #516

**Comment by zblesk** [comment] 2024-01-26 23:06
I have the same error with images not loading. When I run the app locally on Windows, it works. But I'm getting the `13: Permission denied` error on Ubuntu Server 20.04 LTS. 

I've `chown`ed all files to 1000:1000. 
When I `docker exec` into the container's bash, I see this:

![image](https://github.com/zurdi15/romm/assets/4245227/544dacda-6c11-4c68-9ace-f0f9646eff5f)

I.e. the container also sees to correct user. But the problem persists.

**Comment by gantoine** [comment] 2024-03-28 01:28
We've made some changes to permissions in the upcoming 3.1 release, which should hopefully address this issue. If it still happens after the upgrade please comment here!

**Closed by gantoine** 2024-03-28 01:28 UTC
Labels: bug

**Comment by javijuji** [comment] 2024-05-08 23:13
I am still running into this issue. Everything works perfectly except the thumbnails which are correctly getting downloaded into /romm/resources but seems like they cant be accessed by romm

`2024/05/08 23:11:24 [crit] 20#20: *83 stat() "/var/www/html/assets/romm/resources/gba/Pokémon Mystery Dungeon: Red Rescue Team/cover/big.png" failed (13: Permission denied), client: 192.168.100.106, server: localhost, request: "GET /assets/romm/resources/gba/Pok%C3%A9mon%20Mystery%20Dungeon%3A%20Red%20Rescue%20Team/cover/big.png HTTP/1.1", host: "192.168.120.100:8888", referrer: "http://192.168.120.100:8888/platform/1"`

**Comment by MatteoAlberghini** [comment] 2026-06-21 18:28
This issue can still be there if the permissions required to access the resources folders are not passed on to the romm user.

In my case, my NAS requires usergroup 10000 and usually on docker images you can pass:
```
    environment:
      - PUID=1000
      - PGID=10000
```
but romm does not support that. You have to manually edit the etc/group file in the docker container and assign it to romm user

```
docker exec -it romm sh -c "echo 'romm:x:10000:romm' >> /etc/group"
```

EDIT: An actual fix would be to allow passing PUID and PGID or equivalent to the docker compose file, then all permission are respected without manual edits

**Comment by Macleykun** [comment] 2026-08-21 18:22
For anyone stumbeling upon this issue, you no longer have to use the workaround or wait for PUID/PGID support. You can actually use [the `user: ` option in your compose file](https://docs.docker.com/reference/compose-file/services/#user), or the [--user flag](https://docs.podman.io/en/latest/markdown/podman-run.1.html#user-u-user-group).
