### ISSUE TITLE
[Bug] DLC and patch folders 

### ISSUE THREAD

**Issue by gen-angry** [rommapp/romm#1146] opened 2024-09-01 06:04 UTC
**RomM version**
3.5.0

**Describe the bug**
I have DLCs and patches for PC games stored in roms/win/(game)/dlc and roms/win/(game)/patch

Prior to 3.5.0, they used to be part of the file list within their folders. Now they no longer are and they don't show up anywhere else in the game page that I can see. It now just shows the base game files and nothing else.

Clicking download will download just the base game as well. It's like it's completely ignoring sub folders.

**To Reproduce**
Go to a game with /dlc and /patch subfolders.

**Expected behavior**
The DLC and patches included in the file list or even showing that they actually exist anywhere.
Downloading will include patches + dlc/expansions in the generated zip file.

**Screenshots**
![Screenshot 2024-09-01 015421](https://github.com/user-attachments/assets/016579e2-fa22-4c31-b35b-2f835e6064b1)
^ previously, it would show `expansion/Frozen Throne.zip` and `patch/War3TFT_127b_English.zip` in the file list as well.

**Desktop (please complete the following information):**

- OS: Win11
- Browser Firefox
- Version 129

**Additional context**
I read that there were pulls for integrating a new DLC handling system but I can't find any documentation on how it works or if it is finished. None of the game pages itself looks any different.

I could just drop the patches/expansions/dlc into the base game folder but I figured I'd post first to see if something's broken or needs to be documented before I do that to my whole library.

**Comment by gantoine** [comment] 2024-09-01 14:04
Duplicate of #228

**Closed by gantoine** 2024-09-01 14:04 UTC
Labels: bug

**Comment by gen-angry** [comment] 2024-09-01 15:48
> Duplicate of #228

I read that but it doesn't seem to do that, is that only enabled for switch roms?

![Screenshot 2024-09-01 114728](https://github.com/user-attachments/assets/a1bdf1f3-039f-472f-b0cc-f1c9a0c70da9)

File structure is now:
```
/roms/win/
- Warcraft III (WinXP CD)
-- Warcraft III - Reign of Chaos.zip
- Patches
-- Warcraft III (WinXP CD)
--- War3TFT_127b_English.zip
- DLCs
-- Warcraft III (WinXP CD)
--- Warcraft III - The Frozen Throne.zip
```

**Comment by gantoine** [comment] 2024-09-01 16:05
RomM doesn't support DLCs and patches in any way, tossing them into subfolders is good for organizing them, but we don't do anything special with them (yet).

**Comment by Fifthdread** [comment] 2025-01-21 01:35
Can we get this added? I ask because I started using RomM to manage my local GoG install files. When I download with my tool, it creates a folder for the game itself (currently works as expected) and within that folder, a dlc, extras, and patches folder.

It'd be nice to see even super basic subfolder support, so I could download content via RomM.

I currently use a tool called lgogdownloader to download all my GoG content. Running this tool regularly ensures that I have all the latest files at all times, but if I have to move files around every time I run an update, that'll grow old quick. lol

Thanks
