### ISSUE TITLE
[Feature] Viewer/Editor/Admin last login date and time.

### ISSUE THREAD

**Issue by slimshizn** [rommapp/romm#795] opened 2024-04-06 13:01 UTC
**Is your feature request related to a problem? Please describe.**
There is no problem, this would be a great addition to see the last time someone logged in.

**Describe the solution you'd like**
Date and time next to the Viewer/Editor/Admin on the user page.

**Describe alternatives you've considered**
There are no alternatives as there is no date and time anywhere on this page.

**Comment by gantoine** [comment] 2024-04-06 17:03
Duplicate of #618

**Closed by gantoine** 2024-04-06 17:03 UTC
Labels: feature
