### ISSUE TITLE
[Feature] Change IGDB Language / UI Language?

### ISSUE THREAD

**Issue by Nazgile94** [rommapp/romm#1182] opened 2024-09-08 18:44 UTC
any way to change the language?

it pulls the descriptions and data in english - not as bad, but having it in other languages , spanish, german ... etc would be nice to setup

and UI language change :-)

**Comment by gantoine** [comment] 2024-09-08 22:26
Somewhat duplicate of #831, can you move your comment there?

**Closed by gantoine** 2024-09-08 22:26 UTC
Labels: feature
