### ISSUE TITLE
[Feature] Upload Additional Files (Updates, Patches, DLC, Mods, etc)

### ISSUE THREAD

**Issue by onlineinternet** [rommapp/romm#972] opened 2024-07-01 20:38 UTC
**Is your feature request related to a problem? Please describe.**
A lot of games have more files than the base game, such as updates, patches, DLC, and mods/hacks

**Describe the solution you'd like**
It would be nice to have a new tab on the game page where you can upload whatever files you want and write what type of files they are (eg patches, DLC, etc) This is similar to the tab for uploading saved games.

**Describe alternatives you've considered**
The only other option currently is to add files to a game folder or to add them to a compressed file, but the above solution works for all types of folder/file structures and can be done through the romm UI.

**Comment by gantoine** [comment] 2024-07-01 22:46
Duplicate of #228

**Closed by gantoine** 2024-07-01 22:46 UTC
Labels: feature

**Comment by onlineinternet** [comment] 2024-07-02 06:20
I saw that and thought my request was different enough. This one would be through the romm UI and could accept any type of file and not just look for folders specifically marked "patches" or "dlc"
This way would allow for any eventuality and allow the user to label the files as they wish

**Comment by gantoine** [comment] 2024-07-02 13:31
The plan is to do both, just like we do roms and firmware/BIOS today.

**Comment by NeurekaSoftware** [comment] 2026-04-10 18:01
@gantoine I see #228 solves the folder problem, but do we have a way to upload patches, dlc, etc for a single game via the UI?

It seems this feature request was closed prematurely.

**Comment by gantoine** [comment] 2026-04-11 02:02
> do we have a way to upload patches, dlc, etc for a single game via the UI?

we do not, and we don't plan to add it soon. however if someone wants to submit a PR adding it in a clean way yeah we'd accept it.
